version: '3.8'

services:
  TEA-graph:
    build: .
    container_name: TEA-graph
    image: tea-graph
    volumes:
      - .:/work
      - /data01:/data01
      - /home:/home
      - /etc/pam.d:/etc/pam.d
      - /etc/shadow:/etc/shadow
      - /etc/passwd:/etc/passwd
      - /opt/conda/envs:/opt/conda/envs
    ports:
      - 8000:8000
    working_dir: /work
    stdin_open: true
    tty: true
                                                              
